;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "git-content-sync-skill")
(def path ".")
(def version "0.1.9")
(def tag "0.1.9")
(def generated-at "2020-07-17T23:36:23Z")
