;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "repo-check-skill")
(def path ".")
(def version "0.2.0")
(def tag "0.2.0")
(def generated-at "2021-03-17T07:04:28Z")
